export const metadata = {
    title: "Pokemon Memory App",
    description: "Generated by Michelle",
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }